---
# fstab generation with btrfs subvolume mount options
mountOptions:
    - filesystem: btrfs
      options: [ defaults, noatime, compress=zstd:1, space_cache=v2, subvol=@ ]
    - filesystem: default
      options: [ defaults, noatime ]

crypttabOptions:
    - filesystem: luks
      options: [ luks, discard ]

ssdExtraMountOptions:
    - filesystem: btrfs
      options: [ ssd, discard=async ]
    - filesystem: ext4
      options: [ discard ]

efiMountOptions: "umask=0077"

btrfsSubvolumes:
    - mountPoint: /
      subvolume: "@"
    - mountPoint: /home
      subvolume: "@home"
    - mountPoint: /.snapshots
      subvolume: "@snapshots"
