monitor = , preferred, auto, 1
$terminal = alacritty
$menu = wofi --show drun
input {
    kb_layout = it
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    layout = dwindle
}
decoration { rounding = 8 }
exec-once = mako
bind = SUPER, Q, exec, $terminal
bind = SUPER, R, exec, $menu
bind = SUPER, C, killactive,
bind = SUPER, M, exit,
bind = SUPER, E, exec, nemo
bind = SUPER, V, togglefloating,
bind = SUPER, F, fullscreen,
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
