---
# Calamares partition module configuration
efiSystemPartition:      "/boot/efi"
efiSystemPartitionSize:  "512M"
efiSystemPartitionName:  "EFI"

defaultFileSystemType:   "btrfs"
availableFileSystemTypes: ["btrfs", "ext4", "xfs", "f2fs"]

userSwapChoices:
    - none
    - small
    - suspend

initialPartitioningChoice: erase
initialSwapChoice: none

ensureSuspendToDisk: false
neverCreateSwap: false
